spring:
  profiles:
    active: test
---
#开发
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev
---
#测试
spring:
  profiles: test
server:
  port: 81

---
#生产
spring:
  profiles: pro
server:
  port: 82